### ISSUE TITLE
Upstream changes or sync with parent repo

### ISSUE THREAD

**Issue by dimo414** [DaveJarvis/github-email#2]
This repo and https://github.com/paulirish/github-email have diverged (currently 18 ahead, 9 behind) and it's not clear from the README what's different between the two scripts. Particularly since this fork is linked from [WA StackExchange](https://webapps.stackexchange.com/a/167210/13455) it would be helpful to document why this fork should be used instead of the original source. Pulling in the new changes from the parent repo would also help.

Even better would be to upstream your changes, of course :)

**Comment by DaveJarvis** [comment]
> Even better would be to upstream your changes, of course :)

I did make a PR upstream. The original author did not want to add my changes. No explanation given. I believe my implementation is simpler, more flexible, and easier to modify.

**Comment by dimo414** [comment]
To be clear, upstreaming was only one option I was suggesting. The root issue is that the status quo is confusing, particularly since there's nothing in the README explaining what's different between the two scripts.

**Comment by DaveJarvis** [comment]
> Pulling in their subsequent changes would help too

I thought I had looked at that at one point and decided it was too much work to pull in the changes because the branches had diverged too far. If you can figure out a way to bridge the gap, I'd be happy to look over a PR.
