### ISSUE TITLE
npm install instructions are incorrect

### ISSUE THREAD

**Issue by dimo414** [DaveJarvis/github-email#3]
The [README](https://github.com/DaveJarvis/github-email/blob/330f470fef69c03638ce01bf12879c34d3d52f79/README.md) suggests installing via npm, which does not appear to actually install this script. I assume it's installing https://github.com/paulirish/github-email instead but it's unclear.

**Comment by DaveJarvis** [comment]
Good point, I'll update the README to remove the npm installation instructions.

**Comment by dimo414** [comment]
www.npmjs.com/package/github-email is still linked from the sidebar, FYI
